### ISSUE TITLE
How to use this as a generic proxy for all my machines?

### ISSUE THREAD

**Issue by calvinpark** [Hewlett-Packard-ESS/docker-proxy#1]
I'd like to have one machine run `hpess/dockerproxy` as `calvinproxy.company.com` then point my other machines to `calvinproxy.company.com` via `iptables` rules.

For that, how should I set the `iptables`rules be for the client machines? Does this look right?

```
iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to calvinproxy.company.com:3129 -w
iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to calvinproxy.company.com:3130 -w
iptables -t nat -A POSTROUTING -j MASQUERADE
```

**Comment by Stono** [comment]
Looks OK however I don't know about the use of DNS names in iptables.

Also intercepting https is questionable at best .

Karl
