### ISSUE TITLE
Docker run parameters

### ISSUE THREAD

**Issue by calvinpark** [Hewlett-Packard-ESS/docker-proxy#2]
Readme instructs to run the container like this

> sudo docker run -it **--rm** --privileged --net=host -e="cache_peer=your.upstream.proxy" hpess/dockerproxy

This command runs the container and exists. Shouldn't it be this instead?

> sudo docker run -it **-d** --privileged --net=host -e="cache_peer=your.upstream.proxy" hpess/dockerproxy

This way, the container is daemonized and stays alive for others to connect.

**Comment by Stono** [comment]
The readme was demonstrating a single use idempotent container :p

Jokes aside I probably copied and pasted from testing !!
